version: '3'
services:
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - ${LOCATION}/configs:/app/data/configs
      - ${LOCATION}/icons:/app/public/icons
      - ${LOCATION}/data:/data
    ports:
      - '7575:7575'
    env_file:
      - stack.env
