version: "2.1"

name: streamarr

services:
  
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/London
      - JELLYFIN_PublishedServerUrl=${LOCAL_SERVER_IP}:8096 #optional
    volumes:
      - ./jellyfin:/config
      - ${LOCATION}/data/media:/data
    ports:
      - 8096:8096
    restart: unless-stopped
    devices:
      - /dev/dri:/dev/dri
    env_file:
      - stack.env

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/London
    volumes:
      - ./radarr:/config
      - ${LOCATION}/data:/data
    ports:
      - 7878:7878
    restart: unless-stopped
    env_file:
      - stack.env

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/London
    volumes:
      - ./sonarr:/config
      - ${LOCATION}/data:/data
    ports:
      - 8989:8989
    restart: unless-stopped
    env_file:
      - stack.env
      
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/London
    volumes:
      - ./prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
      
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/London
      - WEBUI_PORT=8080
    volumes:
      - ./qbittorrent:/config
      - ${LOCATION}/data/torrents:/data/torrents
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    env_file:
      - stack.env
      
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - LOG_LEVEL=debug
      - TZ=Europe/London
    ports:
      - 5055:5055
    volumes:
      - ./jellyseer:/app/config
    restart: unless-stopped
    
  flaresolverr:
    image: flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/London
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped 
