---
version: "2.1"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - JELLYFIN_PublishedServerUrl=192.168.1.12:8096 #optional
    volumes:
      - ./jellyfin:/config
      - ./jellyfin/series:/data/tvshows
      - ./jellyfin/movies:/data/movies
    ports:
      - 8096:8096
      - 8920:8920 #optional
    restart: unless-stopped
