version: "3.8"
services: 
  cloudflared: 
    image: cloudflare/cloudflared 
    container_name: cloudflare-tunnel 
    restart: unless-stopped 
    command: tunnel run --token ${TOKEN}
    env-file:
      - stack.env
